# Generated by Django 2.0.3 on 2018-03-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('breed', models.CharField(max_length=120)),
                ('age', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=120)),
            ],
        ),
    ]
